### ISSUE TITLE
Line Breaks in Output Variable

### ISSUE THREAD

**Issue by eFloh** [rfennell/vNextBuild#307] opened 2018-04-11 13:32 UTC
### VSTS Extension you are using
*GenerateReleaseNotes (Powershell) Version: 2.21.3*

### Where are you running it?
*on-premise TFS 2017*

### Version of Extension/Task
*Version: 2.21.3*

### Expected behaviour and actual behaviour
- _Expected_: Line Breaks in Template File result in actual line breaks in output
- _Actual_: Line Breaks are replaced by **`n** in the Output variable

### Steps to reproduce the problem
- Set a Template from file (with newlines in windows CRLF format)
- Set an output variable
- use the output variable in another task following this one (e.g. send email-task)

**Comment by eFloh** [comment] 2018-04-11 13:35
Sample Output:
```
### Associated work items`n- *<https://.../_workitems/edit/6989|Bug #6989>* - FC: Direktbestellung: Bedarf bevorzugen`n- *<https://.../_workitems/edit/7250|Feature #7250>* - Direktbestellung aus dem Web erzeugen`n`n### Associated change sets/commits`n- *<https:/.../_versionControl/changeset/14629|CS14629>* - merge: Schreibfehler`n
```

expected:
```
### Associated work items
- *<https://.../_workitems/edit/6989|Bug #6989>* - FC: Direktbestellung: Bedarf bevorzugen
- *<https://.../_workitems/edit/7250|Feature #7250>* - Direktbestellung aus dem Web erzeugen

### Associated change sets/commits
- *<https:/.../_versionControl/changeset/14629|CS14629>* - merge: Schreibfehler

```

**Comment by rfennell** [comment] 2018-04-11 14:07
Yes I have seen this too, my past experiments have not found a working solution.

This needs more experimentation

**Comment by rfennell** [comment] 2018-04-16 10:16
No fix but an update, the issue I think i down to source file being changed to HTML in email, still investigating a fix

**Comment by rfennell** [comment] 2018-04-17 11:42
As per my standard practice I am closing this issue as it is a won't fix. If this issue remains a problem please do not hesitate to re-open it if you think there is value in further discussion

**Closed by rfennell** 2018-04-17 11:42 UTC
Labels: GenerateReleaseNotes (Poweshell version), bug, wontfix

**Comment by alexanderjsx** [comment] 2020-01-08 14:54
This is quite old, but the issue is still there. 
As a workaround I added bash script as next step and stripped `n.

Here is bash code:
```
# release notes were saved into releasenotesvar variable.
# Reassigning it here to local variable
releasenotesvar='$(releasenotesvar)'

# remove `n and save string to new variable
notes=$(echo $releasenotesvar |sed $'s/\x60\x6e//g')

# save notes back to releasenotesvar variable
echo "##vso[task.setvariable variable=releasenotesvar]$notes"
```
