### ISSUE TITLE
GenerateReleaseNotes always pulls commits regardless of whether they are new

### ISSUE THREAD

**Issue by gregpakes** [rfennell/vNextBuild#140] opened 2017-05-31 20:46 UTC
### VSTS Extension you are using
GenerateReleaseNotes

### Where are you running it?
TFS 2017 Update 1

### Version of Extension/Task
latest

### Expected behavior and actual behavior
If you have a build which has not progressed between releases, the same commits will be pulled from it every time.

Example: You have a release with two build artifacts.  The latest release only contains a build from one of the artifacts.  The release notes will contain the commits from the build artifact that isn't new, which would have been included in the previous one.

I don't think i've explained it very well!

**Comment by rfennell** [comment] 2017-06-01 10:27
By design I think!

The way the Poweshell version works is it gets a list of builds/artifacts used in the Release. If a build has not progressed then each release that uses that version of the build will find the same changesets/commits associated with that build.

This is an issue with this way of working, hence building the XPlatGenerate Release notes which tries to use the same mechanism as VSTS UX.

**Comment by rfennell** [comment] 2017-11-14 11:15
@gregpakes  Closing this issue a don't think there is much we can do with the Powershell version and I know you have activally helping mode the xplat version

**Closed by rfennell** 2017-11-14 11:15 UTC
Labels: GenerateReleaseNotes (Poweshell version)
