### ISSUE TITLE
Release notes generation not working

### ISSUE THREAD

**Issue by neutrongenious** [rfennell/vNextBuild#39] opened 2016-08-31 07:49 UTC
Starting: Generate release notes

******************************************************************************
Preparing task execution handler.
Executing the powershell script: C:\a\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\1.4.7\GenerateReleaseNotes.ps1
**Build Number**  : $($build.buildnumber)    
**Build started** : $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$build.startTime)     
**Source Branch** : $($build.sourceBranch)  
###Associated work items  
@@WILOOP@@  
* **$($widetail.fields.'System.WorkItemType') $($widetail.id)** [Assigned by: $($widetail.fields.'System.AssignedTo')]     $($widetail.fields.'System.Title') 
@@WILOOP@@  
###Associated change sets/commits  
@@CSLOOP@@  
* **ID $($csdetail.changesetid)$($csdetail.commitid)** $($csdetail.comment)    
@@CSLOOP@@)

System.ArgumentException: Invalid JSON primitive: .
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
   at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, ErrorRecord& error)
   at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()

System.ArgumentException: Invalid JSON primitive: .
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
   at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, ErrorRecord& error)
   at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()

System.ArgumentException: Invalid JSON primitive: .
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
   at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, ErrorRecord& error)
   at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()

System.Management.Automation.RuntimeException: Cannot convert null to type "System.DateTime". ---> System.Management.Automation.PSInvalidCastException: Cannot convert null to type "System.DateTime".
   at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
   at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   --- End of inner exception stack trace ---

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\a\1\a\artifacts\ReleaseNotes.txt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.PowerShell.Commands.FileSystemContentReaderWriter.CreateStreams(String filePath, String streamName, FileMode fileMode, FileAccess fileAccess, FileShare fileShare, Encoding fileEncoding)
   at Microsoft.PowerShell.Commands.FileSystemProvider.GetContentWriter(String path)

PowerShell script completed with 5 errors.

******************************************************************************

Finishing: Generate release notes

******************************************************************************

**Comment by rfennell** [comment] 2016-08-31 08:31
I think the issue is that you are try to write the output file in a folder that does not exist when the release notes task is run. It does not auto create any sub folders. 

'C:\a\1\a\**artifacts**\ReleaseNotes.txt'

So you need to create the **artifacts** folder first. Or use a folder that already exists. Remember there is no requirement to place the release notes file directly in the artifacts folder, you can build it anywhere and move it with a copy like any other output

**Comment by neutrongenious** [comment] 2016-08-31 15:02
I can double check. but if I enable use default creds then I get above mentioned error.

if I disable that (what is default) then

2016-08-31T07:57:09.7234745Z ##[section]Starting: Generate release notes
2016-08-31T07:57:09.7404752Z Preparing task execution handler.
2016-08-31T07:57:15.1404045Z Executing the powershell script: C:\a\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\1.4.7\GenerateReleaseNotes.ps1
2016-08-31T07:57:15.1404045Z **Build Number**  : $($build.buildnumber)    
2016-08-31T07:57:15.1404045Z **Build started** : $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$build.startTime)     
2016-08-31T07:57:15.1404045Z **Source Branch** : $($build.sourceBranch)  
2016-08-31T07:57:15.1404045Z ###Associated work items  
2016-08-31T07:57:15.1404045Z @@WILOOP@@  
2016-08-31T07:57:15.1404045Z * **$($widetail.fields.'System.WorkItemType') $($widetail.id)** [Assigned by: $($widetail.fields.'System.AssignedTo')]     $($widetail.fields.'System.Title') 
2016-08-31T07:57:15.1404045Z @@WILOOP@@  
2016-08-31T07:57:15.1404045Z ###Associated change sets/commits  
2016-08-31T07:57:15.1404045Z @@CSLOOP@@  
2016-08-31T07:57:15.1404045Z * **ID $($csdetail.changesetid)$($csdetail.commitid)** $($csdetail.comment)    
2016-08-31T07:57:15.1404045Z @@CSLOOP@@)
2016-08-31T07:57:28.2257878Z ##[error]System.Management.Automation.CommandNotFoundException: The term 'Get-ServiceEndPoint' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2016-08-31T07:57:28.2257878Z    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
2016-08-31T07:57:28.2267882Z    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
2016-08-31T07:57:28.2267882Z    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
2016-08-31T07:57:28.2267882Z    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
2016-08-31T07:57:28.2267882Z    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
2016-08-31T07:57:28.2267882Z    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
2016-08-31T07:57:28.2267882Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-08-31T07:57:28.2267882Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-08-31T07:57:29.3545300Z ##[error]System.Management.Automation.MethodInvocationException: Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (401) Unauthorized." ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized.
2016-08-31T07:57:29.3545300Z    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
2016-08-31T07:57:29.3545300Z    at System.Net.WebClient.DownloadString(Uri address)
2016-08-31T07:57:29.3545300Z    at CallSite.Target(Closure , CallSite , Object , Object )
2016-08-31T07:57:29.3545300Z    --- End of inner exception stack trace ---
2016-08-31T07:57:29.3545300Z    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
2016-08-31T07:57:29.3545300Z    at CallSite.Target(Closure , CallSite , Object , Object )
2016-08-31T07:57:29.3545300Z    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
2016-08-31T07:57:29.3545300Z    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
2016-08-31T07:57:29.3545300Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-08-31T07:57:29.5635304Z ##[error]System.Management.Automation.CommandNotFoundException: The term 'Get-ServiceEndPoint' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2016-08-31T07:57:29.5635304Z    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
2016-08-31T07:57:29.5635304Z    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
2016-08-31T07:57:29.5635304Z    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
2016-08-31T07:57:29.5635304Z    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
2016-08-31T07:57:29.5635304Z    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
2016-08-31T07:57:29.5635304Z    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
2016-08-31T07:57:29.5635304Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-08-31T07:57:29.5635304Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-08-31T07:57:29.5745308Z ##[error]System.Management.Automation.MethodInvocationException: Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (401) Unauthorized." ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized.
2016-08-31T07:57:29.5745308Z    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
2016-08-31T07:57:29.5745308Z    at System.Net.WebClient.DownloadString(Uri address)
2016-08-31T07:57:29.5745308Z    at CallSite.Target(Closure , CallSite , Object , Object )
2016-08-31T07:57:29.5745308Z    --- End of inner exception stack trace ---
2016-08-31T07:57:29.5745308Z    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
2016-08-31T07:57:29.5745308Z    at CallSite.Target(Closure , CallSite , Object , Object )
2016-08-31T07:57:29.5745308Z    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
2016-08-31T07:57:29.5755309Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-08-31T07:57:29.7805311Z ##[error]System.Management.Automation.CommandNotFoundException: The term 'Get-ServiceEndPoint' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2016-08-31T07:57:29.7805311Z    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
2016-08-31T07:57:29.7805311Z    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
2016-08-31T07:57:29.7805311Z    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
2016-08-31T07:57:29.7805311Z    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
2016-08-31T07:57:29.7805311Z    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
2016-08-31T07:57:29.7805311Z    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
2016-08-31T07:57:29.7805311Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-08-31T07:57:29.7805311Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-08-31T07:57:29.8045309Z ##[error]System.Management.Automation.MethodInvocationException: Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (401) Unauthorized." ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized.
2016-08-31T07:57:29.8045309Z    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
2016-08-31T07:57:29.8045309Z    at System.Net.WebClient.DownloadString(Uri address)
2016-08-31T07:57:29.8045309Z    at CallSite.Target(Closure , CallSite , Object , Object )
2016-08-31T07:57:29.8045309Z    --- End of inner exception stack trace ---
2016-08-31T07:57:29.8045309Z    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
2016-08-31T07:57:29.8045309Z    at CallSite.Target(Closure , CallSite , Object , Object )
2016-08-31T07:57:29.8045309Z    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
2016-08-31T07:57:29.8045309Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-08-31T07:57:29.9015402Z ##[error]System.Management.Automation.RuntimeException: Cannot convert null to type "System.DateTime". ---> System.Management.Automation.PSInvalidCastException: Cannot convert null to type "System.DateTime".
2016-08-31T07:57:29.9015402Z    at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
2016-08-31T07:57:29.9025315Z    at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
2016-08-31T07:57:29.9025315Z    at CallSite.Target(Closure , CallSite , Object )
2016-08-31T07:57:29.9025315Z    at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
2016-08-31T07:57:29.9025315Z    at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
2016-08-31T07:57:29.9025315Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-08-31T07:57:29.9025315Z    --- End of inner exception stack trace ---
2016-08-31T07:57:29.9855296Z ##[error]PowerShell script completed with 7 errors.
2016-08-31T07:57:29.9865288Z ##[section]Finishing: Generate release notes

**Comment by rfennell** [comment] 2016-08-31 15:57
Are you using it on-prem for with VSTS?
If VSTS and using MS Hosted build agent you definately don't need to use default creds, that is only really for on-prem agent to an on-prem TFS.

Actually you should never really need to use the default cred - that was something I added to try to diagnose some issue one person had

The error System.Management.Automation.RuntimeException: Cannot convert null to type "System.DateTime" is because your template refers to a field that is null (surprise surprise). This is usually that you asked for EndTime and it is not set as the build is still running, try removing this line or using StartDate and see of the problems persist.

**Comment by neutrongenious** [comment] 2016-08-31 19:10
I will try it.
but what about:
2016-08-31T07:57:28.2257878Z ##[error]System.Management.Automation.CommandNotFoundException: The term 'Get-ServiceEndPoint' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

important thing is it's pretty much failing on all build definitions. (which were working fine earlier)

**Comment by rfennell** [comment] 2016-08-31 20:31
Sorry have I misunderstood. Has this task just stopped working?

**Comment by rfennell** [comment] 2016-09-20 20:34
Are you still seeing your issue? If I hear nothing back in a week I will close the issue

**Closed** 2016-09-26 09:02 UTC
Labels: GenerateReleaseNotes
