### ISSUE TITLE
Build Updating Tasks is failing to automatically increase the value of a build variable

### ISSUE THREAD

**Issue by Farzad-Jalali** [rfennell/vNextBuild#239] opened 2018-01-10 16:33 UTC
extension: Build Updating Tasks
from this path: 
https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-BuildUpdating-Tasks#qna

I'm running it on VSTS (the online version of team service )

Version of Extension/Task
version 1.*

basically, I need a counter in my build definition, so I decided to use this extension

here is what I have done:
1. I install the extension (Build Updating Tasks)  
2. I make an empty build.
3. defined variable which is called "buildCounter", set its value to be zero
![image](https://user-images.githubusercontent.com/3695669/34782686-60b34a96-f621-11e7-9eb5-8849d6971a10.png)

4. added only one step to the build definition to auto increment the value of the variable: "Update Build Variable"
![image](https://user-images.githubusercontent.com/3695669/34782738-854a10b0-f621-11e7-8a81-c0b863a84802.png)

5. I use the variable in the buildNumber, so if the build run more than once then I can see the result easily:
![image](https://user-images.githubusercontent.com/3695669/34783200-ceb6fe92-f622-11e7-8c75-525d8665c5be.png)

## Actual behavior:
![image](https://user-images.githubusercontent.com/3695669/34783495-a201a09a-f623-11e7-9c19-6fe4c2396b7c.png)

## The error message in text:

2018-01-10T16:03:46.9475414Z ##[section]Starting: Update Build Variable
2018-01-10T16:03:46.9765867Z ==============================================================================
2018-01-10T16:03:46.9766176Z Task         : Set variable on a build defintion
2018-01-10T16:03:46.9766391Z Description  : Set variable on a build defintion
2018-01-10T16:03:46.9766585Z Version      : 1.7.5
2018-01-10T16:03:46.9766783Z Author       : Richard Fennell
2018-01-10T16:03:46.9767005Z Help         : Version: 1.7.5. [More Information](https://github.com/rfennell/vNextBuild/wiki/BuildTasks-Task/)
2018-01-10T16:03:46.9767266Z ==============================================================================
2018-01-10T16:03:47.0129862Z Preparing task execution handler.
2018-01-10T16:04:16.0497005Z Executing the powershell script: d:\a\_tasks\BuildVariableTask_115030de-9ced-4d2f-ad01-8c42d20d0327\1.7.5\BuildVariableTask.ps1
2018-01-10T16:04:27.7589292Z ##[error]System.Management.Automation.RuntimeException: The property 'value' cannot be found on this object. Verify that the property exists and can be set.
2018-01-10T16:04:27.7592534Z    at CallSite.Target(Closure , CallSite , Object , String )
2018-01-10T16:04:27.7592805Z    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
2018-01-10T16:04:27.7593053Z    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
2018-01-10T16:04:27.7593362Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2018-01-10T16:04:28.5117924Z ##[error]System.Management.Automation.MethodInvocationException: Exception calling "UploadString" with "3" argument(s): "The remote server returned an error: (403) Forbidden." ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
2018-01-10T16:04:28.5120568Z    at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
2018-01-10T16:04:28.5121433Z    at System.Net.WebClient.UploadString(Uri address, String method, String data)
2018-01-10T16:04:28.5121957Z    at CallSite.Target(Closure , CallSite , Object , Object , String , Object )
2018-01-10T16:04:28.5122188Z    --- End of inner exception stack trace ---
2018-01-10T16:04:28.5122463Z    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
2018-01-10T16:04:28.5122796Z    at CallSite.Target(Closure , CallSite , Object , Object , String , Object )
2018-01-10T16:04:28.5123071Z    at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
2018-01-10T16:04:28.5123348Z    at System.Management.Automation.Interpreter.DynamicInstruction`5.Run(InterpretedFrame frame)
2018-01-10T16:04:28.5123657Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2018-01-10T16:04:28.6096814Z ##[error]PowerShell script completed with 2 errors.
2018-01-10T16:04:28.6111379Z ##[section]Finishing: Update Build Variable

**Comment by rfennell** [comment] 2018-01-10 16:37
In the build counter task set the 'variable to update to be **buildcounter** not **$(buildcounter)**

let me know how that works

**Comment by Farzad-Jalali** [comment] 2018-01-11 13:49
Thanks for reply,
I got another error now,

## here is what I did
![image](https://user-images.githubusercontent.com/3695669/34828669-38410b42-f6d6-11e7-83ab-e8eec7363a5f.png)


## here is what I get 

Error Message:
System.Management.Automation.MethodInvocationException: Exception calling "UploadString" with "3" argument(s): "The remote server returned an error: (403) Forbidden." ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.

screenshot:
![image](https://user-images.githubusercontent.com/3695669/34828622-0bac3f0c-f6d6-11e7-898e-9cfd44d516a7.png)

**Comment by rfennell** [comment] 2018-01-11 19:20
That is sort of a know issue, limitation of the out the box experience.

The problem is you are actually updating the build definition not the build instance (as the variable is stored in the definition) . By default the build agent account does not have the rights to do this, you need to grant it extra rights. 

This process is documented in the [WIKI](https://github.com/rfennell/vNextBuild/wiki/BuildTasks-Task) right at the bottom of the page.

Let me know how it goes

**Comment by rfennell** [comment] 2018-01-22 12:10
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it

**Closed by rfennell** 2018-01-22 12:10 UTC
Labels: BuildUtilities
