### ISSUE TITLE
 release notes creation task failed with errors. 

### ISSUE THREAD

**Issue by pagadalacs** [rfennell/vNextBuild#20] opened 2016-06-20 09:17 UTC
Hi,
tried first time the release notes task and it failed with below errors: is there something i am miising ? or i a m doing wrong ? I am running on windows 2005server. 

2016-06-20T06:10:26.4964533Z ##[debug]Loading template file [D:\BuildAgent\_work\1\s\Main\Build\release-template.md]
2016-06-20T06:10:26.5454582Z ##[debug]Processing template
2016-06-20T06:10:27.1405177Z ##[error]Cannot convert null to type "System.DateTime".
 2016-06-20T06:10:27.1745211Z ##[error]Cannot convert null to type "System.DateTime".
 2016-06-20T06:10:27.2835320Z ##[debug]Writing output file [ D:\BuildAgent\_work\1\a\releaseNotes.md].
2016-06-20T06:10:27.3115348Z ##[error]Cannot find drive. A drive with the name ' D' does not exist.

**Comment by rfennell** [comment] 2016-06-20 09:43
I think this is a duplicate of #19 
The sample template I provided had a mistake in it that it asked for the finishtime, this is OK when the task is used within a Release, but does not work for Builds (as the build is in progress)

I have there [edited the build sample](https://github.com/rfennell/vNextBuild/blob/master/SampleTemplates/build-basic-template.md) to read as below, it was my mistake mixing a build and release test example together sorry for the confusion

Build started : $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$build.startTime)

**Comment by rfennell** [comment] 2016-06-20 11:26
My first guess on the Drive D missing error would be the obvious, the build box does not have a drive D:, but I assume it can't be that obvious.

As you use the path 'D:\BuildAgent_work' I am assuming it is your own build agent, not an MS hosted one. So you choose to pick D:

Now you could have set your agent's work folder to 'BuildAgent_work', but this does look like a potential typo, as I would usually expect the path to be 'BuildAgent\_work' as this is the default form. 

So is there a chance it is a typo in your path, a missing \

Can you remote onto the build agent and check the folder structure?

**Comment by pagadalacs** [comment] 2016-06-20 11:48
Thanks for the quick response.  this is my configuration. 
![image](https://cloud.githubusercontent.com/assets/16657058/16192980/1660b5a6-36f5-11e6-8589-38566f089937.png)

in the enviroenment variable :  BUILD_ARTIFACTSTAGINGDIRECTORY: is set to   D:\BuildAgent\_work\1\a

**error is** : 2016-06-20T11:17:01.8675756Z ##[debug]Writing output file [ D:\BuildAgent\_work\1\a\releaseNotes.md].
 
2016-06-20T11:17:01.8785767Z ##[error]Cannot find drive. A drive with the name ' D' does not exist.

**Comment by rfennell** [comment] 2016-06-20 11:56
So, just too check, is this... 
1. a VSTS hosted build agent
2. your own self hosted VSTS agent
3. an on prem TFS 2015.x setup

As it picks up the path from the environment variable I must assume it is correct, if not none of the build would work.

I would suggest trying the output  file as $(System.DefaultWorkingDirectory)\releasenotes.md, then using the copy task to move the results to drops. Maybe the artifacts folder does not exist at the time the task is running, but I have never seen this before.

If you can I would remote onto the agent VM and have a look around

**Comment by pagadalacs** [comment] 2016-06-20 18:28
I am new to tfs build. we have TFS setup on  windows 2008 server. the same is using for builds. I configured the build agent on server.  is it called on Prem setup ? i am not sure.

publish & copy build artifacts task exist before the release task.  anyway, i tried output file as $(System.DefaultWorkingDirectory)\releasenotes.md  

 2016-06-20T18:20:29.3282800Z ##[debug]Loading template file [D:\BuildAgent\_work\1\s]
2016-06-20T18:20:29.3442736Z ##[error]Access to the path 'D:\BuildAgent\_work\1\s' is denied.
 2016-06-20T18:20:29.3692636Z ##[error]Cannot load template file [D:\BuildAgent\_work\1\s] or it is empty
 2016-06-20T18:20:29.3712628Z ##[debug]Writing output file [D:\BuildAgent\_work\1\s\releasenotes.md].


one more i tried output file as D:\temp\releasenotes.md
2016-06-20T16:52:09.8911468Z ##[debug]Loading template file [D:\BuildAgent\_work\1\s]
2016-06-20T16:52:09.9041481Z ##[error]Access to the path 'D:\BuildAgent\_work\1\s' is denied.
2016-06-20T16:52:09.9291506Z ##[error]Cannot load template file [D:\BuildAgent\_work\1\s] or it is empty
 2016-06-20T16:52:09.9301507Z ##[debug]Writing output file [D:\temp\releaseNotes.md].

**Comment by rfennell** [comment] 2016-06-20 19:11
No problem, we are all new to products at some point, what you have what is call an 'on premises' installation, so you own the TFS server and build agent i.e. you set it up, as this the only option for 'on prem'

I assume your build works OK for all the other tasks?

The error looks like one of few things
1. The path is wrong - but that seem unlikely as it is autogenerated
2. The account the build agent is running as has not rights to the drive/folder - again seems strange if the rest of the build is OK - BUT THE ERRORS REALLY LOOK LIKE RIGHTS SO IT IS MY BEST GUESS

So
1. You have place the template file in the declared location in source control?
2. Do you get the same results if you place it inline (see the WIKI on this site for details)
3. Is the build agent running as a service or interactive on the desk top?

I would suggest logging onto the agent VM as the account the build process is running and see what you can see.

**Comment by pagadalacs** [comment] 2016-06-20 20:30
1. yes, its in source control. 2. i will try that next 3. build agent is running as service. i am with my credential in agent VM already. 

The error really looks like some rights issue. 2 days back, we updated the TFS 2015 RC2.1 version. 
Atleast the build agent setup is changed in updated version, its not powershell script for configuring. its windows cmd script and extra there is Runagent.cmd script , that should run always to enable the build agent.  If don't run as admin, i got error in first step, access denied for getting the sources.  and build stopped.

2016-06-20T19:58:47.7097376Z ##[error]Access to the path 'D:\BuildAgent\_work\SourceRootMapping\c0634b7d-4844-4c34-b28c-0969262ce351\9\SourceFolder.json' is denied.
 
I tried running again the Runagent.cmd script with admin rights. other build steps went fine, except your release task. 

2016-06-20T20:04:43.3275348Z ##[debug]Loading template file [D:\BuildAgent\_work\1\s]
 2016-06-20T20:04:43.3395360Z ##[error]Access to the path 'D:\BuildAgent\_work\1\s' is denied.
 2016-06-20T20:04:43.3645385Z ##[error]Cannot load template file [D:\BuildAgent\_work\1\s] or it is empty
 2016-06-20T20:04:43.3665387Z ##[debug]Writing output file [$(BUILD_ARTIFACTSTAGINGDIRECTORY)\releasenotes.md].
 
2016-06-20T20:04:43.3765397Z ##[error]Could not find a part of the path 'D:\BuildAgent\tasks\GenerateReleaseNotes\1.3.22\$(BUILD_ARTIFACTSTAGINGDIRECTORY)\releasenotes.md'.

**Comment by rfennell** [comment] 2016-06-20 21:13
I have seen issues where a folder is created with 'run as admin' and then when you try to access it as a 'non run as admin' you get similar errors. This might be the case between running the build agent via the desktop script or the as a service

One option is to delete the folder in question and start again.

However, that last line of error you show above seems to show that the variable expansion has failed.  You should never see $(BUILD_ARTIFACTSTAGINGDIRECTORY) in the logged path, this could be changed to c:\xxxx or similar

So did the task work prior to upgrading to 2015.2.1?

**Comment by pagadalacs** [comment] 2016-06-21 05:40
i added  this task only   after 2015.2.1 update.  Tried deleting all the folders in build agent , started again, still have the same access issue for release notes only. 
tried for inline template : `$(BUILD_SOURCESDIRECTORY)\Main\Build\release-template.md`
is it the right way ?   got the below error.
2016-06-21T05:32:54.9892182Z ##[debug]Processing template
 2016-06-21T05:32:55.0252254Z ##[error]Method invocation failed because [System.Char] does not contain a method named 'Trim'.
 2016-06-21T05:32:55.0272258Z ##[error]Method invocation failed because [System.Char] does not contain a method named 'Trim'.
2016-06-21T05:32:55.0292262Z ##[error]Method invocation failed because [System.Char] does not contain a method named 'Trim'.

**Comment by rfennell** [comment] 2016-06-21 13:14
If you are using the inline method you expect to see a log
`2016-05-20T06:40:50.0425987Z Executing the powershell script: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\1.99.0\tasks\GenerateReleaseNotes\1.3.22\GenerateReleaseNotes.ps1
2016-05-20T06:40:50.3515793Z ##[debug]collectionUrl = [https://richardfennell.visualstudio.com/]
2016-05-20T06:40:50.3525786Z ##[debug]teamproject = [GitHub]
2016-05-20T06:40:50.3535786Z ##[debug]releaseid = []
2016-05-20T06:40:50.3535786Z ##[debug]buildid = [459]
2016-05-20T06:40:50.3545792Z ##[debug]defname = [Validate-ReleaseNotesTask.Master]
2016-05-20T06:40:50.3555787Z ##[debug]buildnumber = [20160520.1]
2016-05-20T06:40:50.3555787Z ##[debug]In Build mode
2016-05-20T06:40:50.3565784Z ##[debug]Getting build details for BuildID [459]
2016-05-20T06:40:50.6075607Z ##[debug]Getting associated work items for build [459]
2016-05-20T06:40:50.6085609Z ##[debug]Getting associated changesets/commits for build [459]
2016-05-20T06:40:50.6965552Z ##[debug]Using template mode [InLine]
2016-05-20T06:40:50.6975546Z ##[debug]Using in-line template
2016-05-20T06:40:50.7055540Z ##[debug]Processing template
2016-05-20T06:40:50.7285529Z ##[debug]   Starting block WI
2016-05-20T06:40:50.7345521Z ##[debug]      0 items
2016-05-20T06:40:50.8405449Z ##[debug]   Ending block WI
2016-05-20T06:40:50.8435441Z ##[debug]   Starting block CS
2016-05-20T06:40:50.8455430Z ##[debug]      0 items
2016-05-20T06:40:50.8465441Z ##[debug]   Ending block CS
2016-05-20T06:40:50.8475442Z ##[debug]Writing output file [C:\a\1\a\releasenotesinline.md].`

If running in inline mode
* Output file $(Build.ArtifactStagingDirectory)\releasenotesinline.md
* Mode - Inline
* Template is as below

`
#Release notes for build $defname  
Using line line template
**Build Number**  : $($build.buildnumber)    
**Build started** : $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$build.startTime)     
**Source Branch** : $($build.sourceBranch)  
###Associated work items  
@@WILOOP@@  
* **$($widetail.fields.'System.WorkItemType') $($widetail.id)** [Assigned by: $($widetail.fields.'System.AssignedTo')]     $($widetail.fields.'System.Title') 
@@WILOOP@@  
###Associated change sets/commits  
@@CSLOOP@@  
* **ID $($csdetail.changesetid)$($csdetail.commitid)** $($csdetail.comment)    
@@CSLOOP@@
`

The errors you have now seem to be that the template is missing or you have no text to process.

I will update the wiki to try to explain using the inline method more clearly

**Comment by pagadalacs** [comment] 2016-06-21 13:51
Thanks for the instructions. YES, inline - mode is working for me. Its good to see working finally. is it so that output file won't have any formatting when generated with inline ? is it possible to specify the output file in some other format than .md ?

**Comment by rfennell** [comment] 2016-06-21 14:19
Sorry I only support markdown (MD) as a format, feel tree to fork the code and add a different one of you wish :)

There is no difference in what you get between inline or file based operations assuming the template is the same. It is just down to whether you wish to source control your template or just have it as a build parameter.

So I suspect the problem all along has been the source template (file) not ending up in the location you expect.

Glad you have something working now

**Closed** 2016-06-27 17:44 UTC
Labels: duplicate

**Comment by mlooise** [comment] 2017-01-23 16:00
Hi @rfennell ,

I have kind of the same problem as @pagadalacs had. It seems to me that the template file is by default taken from the artifacts directory (in my case  ##[error]System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\BATest\_work\2\a\releasenotes.md) . I have included the template in my Git repo to be used and can select it fine. (see below). However I think the tool assumes that this file will end up in de artifact dir (as it would maybe eventually) but this is only the case after the build finishes (e.g. when the release is made. Is this maybe the assumption? We , for now, work with the inline mode which does work. 

Maybe its an idea to rework the source directory for the template?

Regards, martin

![releasenotes](https://cloud.githubusercontent.com/assets/2109791/22211364/112fdace-e18d-11e6-87a8-8026c5b0bbac.png)
