### ISSUE TITLE
Error running Generate Release Notes on Mac 'A supported task execution handler was not found'

### ISSUE THREAD

**Issue by darkice-matt-crombie** [rfennell/vNextBuild#206] opened 2017-11-14 01:36 UTC
### VSTS Extension you are using
*There are a number of VSTS extension in this repo so please say which one you are using, and if an extension contains multiple tasks which task also*

Task         : Generate Release Notes
Version      : 2.11.4

### Where are you running it?
*VSTS or on-premise TFS (if so what version)*
VSTS with Mac build host.

  System Version:	macOS 10.12.6 (16G1036)
  Kernel Version:	Darwin 16.7.0

### Version of Extension/Task
*I assume it is the currently public version, if you are using an older version on-premises let me know, but the answer will probably involve upgrading to the currently public version*

Details of run:

2017-11-14T01:24:07.7817090Z ##[section]Starting: Generate release notes
2017-11-14T01:24:07.7862670Z ==============================================================================
2017-11-14T01:24:07.7875870Z Task         : Generate Release Notes
2017-11-14T01:24:07.7889300Z Description  : Generates a release notes file in a format of your choice
2017-11-14T01:24:07.7903520Z Version      : 2.11.4
2017-11-14T01:24:07.7917470Z Author       : Black Marble
2017-11-14T01:24:07.7932490Z Help         : Version: 2.11.4. [More Information](https://github.com/rfennell/vNextBuild/wiki/GenerateReleaseNotes%20-Tasks/)
2017-11-14T01:24:07.7946280Z ==============================================================================
2017-11-14T01:24:07.8574290Z ##[error]A supported task execution handler was not found. This error usually means the task does not carry an implementation that is compatible with your current operating system. Contact the task author for more details.
2017-11-14T01:24:07.8641950Z ##[section]Finishing: Generate release notes

### Expected behavior and actual behavior

Generates release notes successfully. Instead error is displayed:

A supported task execution handler was not found. This error usually means the task does not carry an implementation that is compatible with your current operating system. Contact the task author for more details.

### Steps to reproduce the problem

Add a task in VSTS with any configuration and run.

I've tried with different configuration options but it doesn't seem to make a difference.

**Comment by rfennell** [comment] 2017-11-14 10:18
The problem is you have selected my original Powershell based VSTS Extension, which is failing as there is no Powershell on a Mac (well not the version of Powershell it needs, there maybe Powershell Core on your Mac these days but this is not enough).

I decided, after a good deal of thought, to not add Non-windows support to this extension. In the end I decided to create a second extension that is Node.JS based and hence cross platform. You can find this [in the marketplace too](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes)

The main reason for this choice is this Powershell based version does all the logic for finding associated changeset/commits and work items itself, there was no other option when it was written. The newer XPlat version uses newer Microsoft provided API calls, so it behaviour is a little different. Also there are breaking changes in the templating file format. 

As some people make heavy use of the older Powershell version and I did not want to impose breaking changes on them. Having two separate extensions means they can choose to move to Xplat if and when the want. They are both being updated as needed.

So please try the [Xplat version](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes). 

So I will close this issue, if you have problems with the Xplat extension please open a new issue for that extensions specfically, it makes tacking support easier

**Closed by rfennell** 2017-11-14 10:18 UTC
Labels: GenerateReleaseNotes (Poweshell version)
