### ISSUE TITLE
GenerateReleaseNotes - maxJsonLength Exception

### ISSUE THREAD

**Issue by gigeld** [rfennell/vNextBuild#242] opened 2018-01-13 00:29 UTC
Occasionally we are getting this error while running GenerateReleaseNotes in VSTS
"Error during serialization or deserialization using the JSON JavaScriptSerializer. The length of the string exceeds the value set on the maxJsonLength property."

Can we change the value of this property?

Thanks

**Comment by rfennell** [comment] 2018-01-13 11:33
Can't see a reason to not add that, I will probably add it as an advanced option

**Comment by rfennell** [comment] 2018-01-13 15:53
Turns out that this is a bit more complex than I expected. The **ConvertFrom-Json** cmdlet that is used to do this conversion does not take **maxJsonLength** property. 

This means that refactoring is required to use a different deserialisation method, the problem is all the code samples I can find return the JSON data in different PS Object formats to the **ConvertFrom-Json** cmdlet. Need to work out if this is going to be an issue

**Comment by gigeld** [comment] 2018-01-15 00:15
Thank you for looking into it!

**Comment by rfennell** [comment] 2018-01-19 11:28
This has been fixed in 2.15.4

It uses new code to do the deserialisation of the JSON as opposed to **ConvertFrom-Json** CmdLet. This new code allows JSON blocks up to 100Mb as opposed to 2Mb

**Closed by rfennell** 2018-01-19 11:28 UTC
Labels: GenerateReleaseNotes (Poweshell version), enhancement

**Comment by gigeld** [comment] 2018-01-21 23:55
Thank you for your great support!
