### ISSUE TITLE
Work Item Details printed in output md twice

### ISSUE THREAD

**Issue by willsmith28** [rfennell/vNextBuild#155] opened 2017-07-31 14:55 UTC
### VSTS Extension you are using
*Generate Release Notes Build Task *

### Where are you running it?
*VSTS 

### Version of Extension/Task
*2.10.2*

### Expected behavior and actual behavior
Change set items display normally but Work Item details are printed in output md twice.

### Steps to reproduce the problem
I'm using an inline template shown below

> ### Associated work items  
> @@WILOOP@@  
> * **$($widetail.fields.'System.WorkItemType') $($widetail.id)** $($widetail.fields.'System.Title') 
> @@WILOOP@@  
> ### Associated change sets/commits  
> @@CSLOOP@@  
> *  $($csdetail.comment)   
> @@CSLOOP@@

but it prints each work item twice

### Associated work items  
* **User Story 15** As a user I want to see details about the updates to this site 
* **User Story 15** As a user I want to see details about the updates to this site 
### Associated change sets/commits  
*  Merged PR 8: Do a thing
Do a thing
Related work items: #15   
*  Do a thing

**Comment by rfennell** [comment] 2017-08-02 09:10
What do you see if you enable more detailed logging sets a global variable of system.debug to true?

I am sure someone reported something like this before, but can't find an issue, so guess need to look into it again.

**Comment by willsmith28** [comment] 2017-08-03 19:55
When setting system.debug to true the results are still the same.
Its the powershell version.

**Comment by Danco-Reassure** [comment] 2017-08-04 07:54
Hi Richard,

We have been getting this issue as well.
Our builds have multiple artifacts, and multipel commits can point to the same work-item..

Ive done some digging, and I can see that the _api call itself is returning duplicate entries.
Ive raised this in the VSTS forum here - bu tim not sure what the response/turnaround is usually like on this..

https://developercommunity.visualstudio.com/content/problem/89315/vsts-build-workitem-rest-api-returning-duplicates.html

Whether its possible for you to amend the powershell to get a distinct list from VSTS in the meantime i'm not sure whether you would be prepared/happy to do that?

Thanks
Dan

**Comment by rfennell** [comment] 2017-08-04 09:15
The reason I asked for you to run with more logging was so we could see if the issue from the logging firstly the complete list of WI/CS returned by the API calls. The task should then trim the list to remove duplicates before running against the template.

My guess is we need different de-duplication logic, As this extension was originally created for a single build I think there could be an issue when used against a release which can contain many builds that cross reference the same WI/CS

**Comment by willsmith28** [comment] 2017-08-04 14:35
Here is the log
> 2017-08-04T14:33:23.2159011Z ##[debug]PowerShellHandler.Execute - AddCommand(C:\agent\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\2.10.2\GenerateReleaseNotes.ps1)
2017-08-04T14:33:23.2159011Z ##[debug]PowerShellHandler.Execute - Add inputParameters
2017-08-04T14:33:23.2159011Z ##[debug]PowerShellHandler.Execute - AddParameter(outputfile=C:\agent\_work\r2\a\releasenotes.md)
2017-08-04T14:33:23.2159011Z ##[debug]PowerShellHandler.Execute - AddParameter(outputVariableName=)
2017-08-04T14:33:23.2159011Z ##[debug]PowerShellHandler.Execute - AddParameter(templateLocation=InLine)
2017-08-04T14:33:23.2164007Z ##[debug]PowerShellHandler.Execute - AddParameter(templatefile=C:\agent\_work\r2\a)
2017-08-04T14:33:23.2164007Z ##[debug]PowerShellHandler.Execute - AddParameter(inlinetemplate=**Release notes for release $defname**
2017-08-04T14:33:23.2164007Z **Release Number**  : $($Release.ReleaseName)    
2017-08-04T14:33:23.2164007Z **Release completed** $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$release.modifiedOn)
2017-08-04T14:33:23.2164007Z 
2017-08-04T14:33:23.2164007Z ###Associated work items  
2017-08-04T14:33:23.2164007Z @@WILOOP@@  
2017-08-04T14:33:23.2164007Z * **$($widetail.fields.'System.WorkItemType') $($widetail.id)** $($widetail.fields.'System.Title') 
2017-08-04T14:33:23.2164007Z @@WILOOP@@  
2017-08-04T14:33:23.2164007Z ### Associated change sets/commits  
2017-08-04T14:33:23.2164007Z @@CSLOOP@@  
2017-08-04T14:33:23.2164007Z * $($csdetail.comment)    
2017-08-04T14:33:23.2164007Z @@CSLOOP@@)
2017-08-04T14:33:23.2164007Z ##[debug]PowerShellHandler.Execute - AddParameter(usedefaultcreds=false)
2017-08-04T14:33:23.2164007Z ##[debug]PowerShellHandler.Execute - AddParameter(emptySetText=None)
2017-08-04T14:33:23.2164007Z ##[debug]PowerShellHandler.Execute - AddParameter(generateForOnlyPrimary=false)
2017-08-04T14:33:23.2164007Z ##[debug]PowerShellHandler.Execute - AddParameter(generateForCurrentRelease=********)
2017-08-04T14:33:23.2164007Z ##[debug]PowerShellHandler.Execute - AddParameter(overrideStageName=)
2017-08-04T14:33:23.3215763Z ##[debug]PowerShellHandler.Execute - Invoke
2017-08-04T14:33:23.3996931Z ##[debug]Loading module from path 'C:\agent\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\2.10.2\GenerateReleaseNotes.psm1'.
2017-08-04T14:33:23.4197959Z ##[debug]
2017-08-04T14:33:23.4202785Z    public enum Mode
2017-08-04T14:33:23.4202785Z    {
2017-08-04T14:33:23.4202785Z       BODY,
2017-08-04T14:33:23.4202785Z       WI,
2017-08-04T14:33:23.4202785Z       CS,
2017-08-04T14:33:23.4202785Z       BUILD
2017-08-04T14:33:23.4202785Z    }
2017-08-04T14:33:23.6074531Z ##[debug]Exporting function 'Get-BuildWorkItems'.
2017-08-04T14:33:23.6074531Z ##[debug]Exporting function 'Get-BuildChangeSets'.
2017-08-04T14:33:23.6074531Z ##[debug]Exporting function 'Get-Detail'.
2017-08-04T14:33:23.6074531Z ##[debug]Exporting function 'Get-Build'.
2017-08-04T14:33:23.6074531Z ##[debug]Exporting function 'Get-BuildsByDefinitionId'.
2017-08-04T14:33:23.6074531Z ##[debug]Exporting function 'Get-ReleaseDefinitionByName'.
2017-08-04T14:33:23.6074531Z ##[debug]Exporting function 'Get-Release'.
2017-08-04T14:33:23.6074531Z ##[debug]Exporting function 'Get-BuildReleaseArtifacts'.
2017-08-04T14:33:23.6074531Z ##[debug]Exporting function 'Add-Space'.
2017-08-04T14:33:23.6074531Z ##[debug]Exporting function 'Invoke-GetCommand'.
2017-08-04T14:33:23.6074531Z ##[debug]Exporting function 'Render'.
2017-08-04T14:33:23.6079575Z ##[debug]Exporting function 'Get-Template'.
2017-08-04T14:33:23.6079575Z ##[debug]Exporting function 'Get-Mode'.
2017-08-04T14:33:23.6079575Z ##[debug]Exporting function 'Add-StackItem'.
2017-08-04T14:33:23.6079575Z ##[debug]Exporting function 'Invoke-Template'.
2017-08-04T14:33:23.6079575Z ##[debug]Exporting function 'Get-BuildDataSet'.
2017-08-04T14:33:23.6079575Z ##[debug]Exporting function 'Get-ReleaseByDefinitionId'.
2017-08-04T14:33:23.6079575Z ##[debug]Importing function 'Add-Space'.
2017-08-04T14:33:23.6079575Z ##[debug]Importing function 'Add-StackItem'.
2017-08-04T14:33:23.6079575Z ##[debug]Importing function 'Get-Build'.
2017-08-04T14:33:23.6079575Z ##[debug]Importing function 'Get-BuildChangeSets'.
2017-08-04T14:33:23.6079575Z ##[debug]Importing function 'Get-BuildDataSet'.
2017-08-04T14:33:23.6084528Z ##[debug]Importing function 'Get-BuildReleaseArtifacts'.
2017-08-04T14:33:23.6084528Z ##[debug]Importing function 'Get-BuildsByDefinitionId'.
2017-08-04T14:33:23.6084528Z ##[debug]Importing function 'Get-BuildWorkItems'.
2017-08-04T14:33:23.6084528Z ##[debug]Importing function 'Get-Detail'.
2017-08-04T14:33:23.6084528Z ##[debug]Importing function 'Get-Mode'.
2017-08-04T14:33:23.6084528Z ##[debug]Importing function 'Get-Release'.
2017-08-04T14:33:23.6084528Z ##[debug]Importing function 'Get-ReleaseByDefinitionId'.
2017-08-04T14:33:23.6084528Z ##[debug]Importing function 'Get-ReleaseDefinitionByName'.
2017-08-04T14:33:23.6084528Z ##[debug]Importing function 'Get-Template'.
2017-08-04T14:33:23.6084528Z ##[debug]Importing function 'Invoke-GetCommand'.
2017-08-04T14:33:23.6084528Z ##[debug]Importing function 'Invoke-Template'.
2017-08-04T14:33:23.6084528Z ##[debug]Importing function 'Render'.
2017-08-04T14:33:23.6169687Z ##[debug]collectionUrl = [https://willsmith28.visualstudio.com/]
2017-08-04T14:33:23.6174666Z ##[debug]teamproject = [MyFirstProject]
2017-08-04T14:33:23.6174666Z ##[debug]releaseid = [44]
2017-08-04T14:33:23.6174666Z ##[debug]releasedefid = [3]
2017-08-04T14:33:23.6174666Z ##[debug]stageName = [Environment 1]
2017-08-04T14:33:23.6179684Z ##[debug]overrideStageName = []
2017-08-04T14:33:23.6179684Z ##[debug]buildid = [50]
2017-08-04T14:33:23.6179684Z ##[debug]builddefname = [MyFirstProject-ASP.NET (PREVIEW)-CI]
2017-08-04T14:33:23.6179684Z ##[debug]releasedefname = [release]
2017-08-04T14:33:23.6184658Z ##[debug]buildnumber = [20170803.4]
2017-08-04T14:33:23.6184658Z ##[debug]outputVariableName = []
2017-08-04T14:33:23.6184658Z ##[debug]generateForOnlyPrimary = [false]
2017-08-04T14:33:23.6184658Z ##[debug]generateForCurrentRelease = [********]
2017-08-04T14:33:23.6189650Z ##[debug]In Release mode
2017-08-04T14:33:23.6244678Z ##[debug]Only processing current release
2017-08-04T14:33:23.6280543Z ##[debug]Getting details of release [44] from server [https://willsmith28.visualstudio.com//MyFirstProject]
2017-08-04T14:33:23.7403267Z ##[debug]Loading module from path 'C:\agent\externals\vstshost\Microsoft.TeamFoundation.DistributedTask.Task.LegacySDK.dll'.
2017-08-04T14:33:23.7563702Z ##[debug]Importing cmdlet 'Invoke-ResultPublisher'.
2017-08-04T14:33:23.7563702Z ##[debug]Importing cmdlet 'Publish-TestResults'.
2017-08-04T14:33:23.7563702Z ##[debug]Importing cmdlet 'Add-BuildArtifactLink'.
2017-08-04T14:33:23.7563702Z ##[debug]Importing cmdlet 'Add-BuildAttachment'.
2017-08-04T14:33:23.7563702Z ##[debug]Importing cmdlet 'Convert-String'.
2017-08-04T14:33:23.7563702Z ##[debug]Importing cmdlet 'Copy-BuildArtifact'.
2017-08-04T14:33:23.7563702Z ##[debug]Importing cmdlet 'Get-JavaDevelopmentKitPath'.
2017-08-04T14:33:23.7563702Z ##[debug]Importing cmdlet 'Get-MSBuildLocation'.
2017-08-04T14:33:23.7568720Z ##[debug]Importing cmdlet 'Get-ServiceEndpoint'.
2017-08-04T14:33:23.7568720Z ##[debug]Importing cmdlet 'Get-TaskVariable'.
2017-08-04T14:33:23.7568720Z ##[debug]Importing cmdlet 'Get-TfsClientCredentials'.
2017-08-04T14:33:23.7568720Z ##[debug]Importing cmdlet 'Get-ToolPath'.
2017-08-04T14:33:23.7568720Z ##[debug]Importing cmdlet 'Get-VisualStudioPath'.
2017-08-04T14:33:23.7568720Z ##[debug]Importing cmdlet 'Get-VssConnection'.
2017-08-04T14:33:23.7568720Z ##[debug]Importing cmdlet 'Invoke-Ant'.
2017-08-04T14:33:23.7568720Z ##[debug]Importing cmdlet 'Invoke-BatchScript'.
2017-08-04T14:33:23.7568720Z ##[debug]Importing cmdlet 'Invoke-Maven'.
2017-08-04T14:33:23.7568720Z ##[debug]Importing cmdlet 'Invoke-MSBuild'.
2017-08-04T14:33:23.7568720Z ##[debug]Importing cmdlet 'Invoke-Tool'.
2017-08-04T14:33:23.7568720Z ##[debug]Importing cmdlet 'Invoke-VSTest'.
2017-08-04T14:33:23.7568720Z ##[debug]Importing cmdlet 'Publish-BuildArtifact'.
2017-08-04T14:33:23.7573703Z ##[debug]Importing cmdlet 'Register-XamarinLicense'.
2017-08-04T14:33:23.7573703Z ##[debug]Importing cmdlet 'Unregister-XamarinLicense'.
2017-08-04T14:33:23.7573703Z ##[debug]Importing cmdlet 'Get-X509Certificate'.
2017-08-04T14:33:23.7573703Z ##[debug]Importing cmdlet 'Invoke-DeployTestAgent'.
2017-08-04T14:33:23.7573703Z ##[debug]Importing cmdlet 'Invoke-RunDistributedTests'.
2017-08-04T14:33:23.7573703Z ##[debug]Importing cmdlet 'Invoke-BlockEnvironment'.
2017-08-04T14:33:23.7573703Z ##[debug]Importing cmdlet 'Copy-FilesToAzureBlob'.
2017-08-04T14:33:23.7573703Z ##[debug]Importing cmdlet 'Copy-FilesToTargetMachine'.
2017-08-04T14:33:23.7573703Z ##[debug]Importing cmdlet 'Copy-ToAzureMachines'.
2017-08-04T14:33:23.7573703Z ##[debug]Importing cmdlet 'Remove-Environment'.
2017-08-04T14:33:23.7573703Z ##[debug]Importing cmdlet 'Remove-EnvironmentResources'.
2017-08-04T14:33:23.7573703Z ##[debug]Importing cmdlet 'Complete-EnvironmentOperation'.
2017-08-04T14:33:23.7573703Z ##[debug]Importing cmdlet 'Complete-EnvironmentResourceOperation'.
2017-08-04T14:33:23.7578725Z ##[debug]Importing cmdlet 'Complete-ResourceOperation'.
2017-08-04T14:33:23.7578725Z ##[debug]Importing cmdlet 'Get-Environment'.
2017-08-04T14:33:23.7578725Z ##[debug]Importing cmdlet 'Get-EnvironmentProperty'.
2017-08-04T14:33:23.7578725Z ##[debug]Importing cmdlet 'Get-EnvironmentResources'.
2017-08-04T14:33:23.7578725Z ##[debug]Importing cmdlet 'Get-ExternalIpAddress'.
2017-08-04T14:33:23.7578725Z ##[debug]Importing cmdlet 'Get-ParsedSessionVariables'.
2017-08-04T14:33:23.7578725Z ##[debug]Importing cmdlet 'Get-ProviderData'.
2017-08-04T14:33:23.7578725Z ##[debug]Importing cmdlet 'Invoke-EnvironmentOperation'.
2017-08-04T14:33:23.7578725Z ##[debug]Importing cmdlet 'Invoke-ResourceOperation'.
2017-08-04T14:33:23.7578725Z ##[debug]Importing cmdlet 'Invoke-PsOnRemote'.
2017-08-04T14:33:23.7578725Z ##[debug]Importing cmdlet 'New-OperationLog'.
2017-08-04T14:33:23.7578725Z ##[debug]Importing cmdlet 'Copy-FilesToRemote'.
2017-08-04T14:33:23.7578725Z ##[debug]Importing cmdlet 'Register-Environment'.
2017-08-04T14:33:23.7578725Z ##[debug]Importing cmdlet 'Register-EnvironmentDefinition'.
2017-08-04T14:33:23.7583722Z ##[debug]Importing cmdlet 'Register-Provider'.
2017-08-04T14:33:23.7583722Z ##[debug]Importing cmdlet 'Register-ProviderData'.
2017-08-04T14:33:23.7583722Z ##[debug]Importing cmdlet 'Invoke-UnblockEnvironment'.
2017-08-04T14:33:23.7583722Z ##[debug]Importing cmdlet 'Add-TaskIssue'.
2017-08-04T14:33:23.7583722Z ##[debug]Importing cmdlet 'Complete-Task'.
2017-08-04T14:33:23.7583722Z ##[debug]Importing cmdlet 'Find-Files'.
2017-08-04T14:33:23.7583722Z ##[debug]Importing cmdlet 'Get-LocalizedString'.
2017-08-04T14:33:23.7583722Z ##[debug]Importing cmdlet 'Set-TaskProgress'.
2017-08-04T14:33:23.7583722Z ##[debug]Importing cmdlet 'Set-TaskVariable'.
2017-08-04T14:33:23.7583722Z ##[debug]Importing cmdlet 'Write-TaskDetail'.
2017-08-04T14:33:23.7583722Z ##[debug]Importing cmdlet 'Enable-CodeCoverage'.
2017-08-04T14:33:23.7583722Z ##[debug]Importing cmdlet 'Publish-CodeCoverage'.
2017-08-04T14:33:23.7593710Z ##[debug]Exporting cmdlet 'Add-BuildArtifactLink'.
2017-08-04T14:33:23.7593710Z ##[debug]Exporting cmdlet 'Add-BuildAttachment'.
2017-08-04T14:33:23.7593710Z ##[debug]Exporting cmdlet 'Convert-String'.
2017-08-04T14:33:23.7593710Z ##[debug]Exporting cmdlet 'Copy-BuildArtifact'.
2017-08-04T14:33:23.7593710Z ##[debug]Exporting cmdlet 'Get-JavaDevelopmentKitPath'.
2017-08-04T14:33:23.7593710Z ##[debug]Exporting cmdlet 'Get-MSBuildLocation'.
2017-08-04T14:33:23.7593710Z ##[debug]Exporting cmdlet 'Get-ServiceEndpoint'.
2017-08-04T14:33:23.7593710Z ##[debug]Exporting cmdlet 'Get-TaskVariable'.
2017-08-04T14:33:23.7593710Z ##[debug]Exporting cmdlet 'Get-TfsClientCredentials'.
2017-08-04T14:33:23.7593710Z ##[debug]Exporting cmdlet 'Get-ToolPath'.
2017-08-04T14:33:23.7593710Z ##[debug]Exporting cmdlet 'Get-VisualStudioPath'.
2017-08-04T14:33:23.7598710Z ##[debug]Exporting cmdlet 'Get-VssConnection'.
2017-08-04T14:33:23.7598710Z ##[debug]Exporting cmdlet 'Invoke-Ant'.
2017-08-04T14:33:23.7598710Z ##[debug]Exporting cmdlet 'Invoke-BatchScript'.
2017-08-04T14:33:23.7598710Z ##[debug]Exporting cmdlet 'Invoke-Maven'.
2017-08-04T14:33:23.7598710Z ##[debug]Exporting cmdlet 'Invoke-MSBuild'.
2017-08-04T14:33:23.7598710Z ##[debug]Exporting cmdlet 'Invoke-Tool'.
2017-08-04T14:33:23.7598710Z ##[debug]Exporting cmdlet 'Invoke-VSTest'.
2017-08-04T14:33:23.7598710Z ##[debug]Exporting cmdlet 'Publish-BuildArtifact'.
2017-08-04T14:33:23.7598710Z ##[debug]Exporting cmdlet 'Register-XamarinLicense'.
2017-08-04T14:33:23.7598710Z ##[debug]Exporting cmdlet 'Unregister-XamarinLicense'.
2017-08-04T14:33:23.7598710Z ##[debug]Exporting cmdlet 'Get-X509Certificate'.
2017-08-04T14:33:23.7699242Z ##[debug]Processed: ##vso[task.setprogress value=-1;] 
2017-08-04T14:33:24.0782932Z ##[debug]Discovered [1] releases for processing after checking a total of [1] releases
2017-08-04T14:33:24.0902924Z ##[debug]The artifact [MyFirstProject-ASP.NET (PREVIEW)-CI] is a VSTS build, will attempt to find associated commits/changesets and work items
2017-08-04T14:33:24.0953125Z ##[debug]Found 1 build artifacts to check for builds that fall in range
2017-08-04T14:33:24.0958130Z ##[debug]Checking build artifacts for the Build Defintion ID 3
2017-08-04T14:33:25.1120528Z ##[debug]    Getting build details for BuildID [50]
2017-08-04T14:33:25.1120528Z ##[debug]        Getting associated work items for build [50]
2017-08-04T14:33:25.1120528Z ##[debug]        Getting associated changesets/commits for build [50]
2017-08-04T14:33:25.2738587Z ##[debug]Using template mode [InLine]
2017-08-04T14:33:25.2738587Z ##[debug]Using in-line template
2017-08-04T14:33:25.2889115Z ##[debug]Processing template
2017-08-04T14:33:25.2929081Z ##[debug]There are [1] builds to process
2017-08-04T14:33:25.3034062Z ##[debug]From [1] releases
2017-08-04T14:33:25.4077195Z ##[debug]   Starting block WI
2017-08-04T14:33:25.4223589Z ##[debug]      2 items
2017-08-04T14:33:25.4338644Z ##[debug]      Getting first workitem 15
2017-08-04T14:33:25.4669546Z ##[debug]      Getting next workitem 15
2017-08-04T14:33:25.4734510Z ##[debug]   Ending block WI
2017-08-04T14:33:25.4829781Z ##[debug]   Starting block CS
2017-08-04T14:33:25.4864832Z ##[debug]      2 items
2017-08-04T14:33:25.4884791Z ##[debug]      Getting first changeset/commit 
2017-08-04T14:33:25.4989807Z ##[debug]      Getting next changeset/commit 
2017-08-04T14:33:25.4994807Z ##[debug]   Ending block CS
2017-08-04T14:33:25.5004779Z ##[debug]Writing output file [C:\agent\_work\r2\a\releasenotes.md].
2017-08-04T14:33:25.5099780Z ##[debug]Skipping setting output variable name as parameter was not set.
2017-08-04T14:33:25.5400111Z ##[section]Finishing: Generate release notes

**Comment by Danco-Reassure** [comment] 2017-09-12 07:14
Hello Richard,

The VSTS API fix to prevent duplicates has apparently been done now and is awaiting release:

Will re-asses this issue once that fix is live.

https://developercommunity.visualstudio.com/content/problem/89315/vsts-build-workitem-rest-api-returning-duplicates.html

**Comment by rfennell** [comment] 2017-11-14 11:11
I am trying to tidy up the list of issues, so is there any new information on this? I have not changed this task to use a newer version of an API.

The other thing I would suggest is trying my crossplatform release notes extension I also have in the marketplace.

If I hear nothing I will close this issue is about 7 days, if the issue reoccurs after this time please feel free to reopen it

**Comment by Danco-Reassure** [comment] 2017-11-15 17:05
Hi Richard,

I can confirm the MS API changes are Live and the existing plugin no longer ever seems to output any duplicates.

Thank you I believe this issue can be closed.

**Comment by rfennell** [comment] 2017-11-16 14:30
Thanks for the update

**Closed by rfennell** 2017-11-16 14:30 UTC
Labels: bug, GenerateReleaseNotes (Poweshell version)
