### ISSUE TITLE
GenerateReleaseNotes not working for external git repos

### ISSUE THREAD

**Issue by turowicz** [rfennell/vNextBuild#48] opened 2016-11-08 11:15 UTC
Firstly I'd like to say that this tool is amazing and works great with everything in VSTS.

The problem I'm currently having is that there are some things that I have to build from custom / external git repositories and the build step results in an empty markdown file.

**Comment by rfennell** [comment] 2016-11-08 17:23
Ok I have done some quick testing

1. Created a new github repo
2. Added an issue to the repo
3. Added a basic .NET solution and commit putting the #ID for the issue in the comment
4. Setup a VSTS build using the generate release notes

The release notes were created but as you saw the .MD file was empty. This is for a couple of reasons

- There are no work item listed as there is VSTS work items associated with the commit, it is a Github issue not a VSTS WI
- The build does show an associated commit, just the word **ID**. So we know it found the changeset, but has not details.

If you check the log you see the follow

```
2016-11-08T16:52:09.8482011Z ##[warning]Unable to get details of changeset/commit as it is not stored in TFS/VSTS
2016-11-08T16:52:09.8502002Z ##[warning]For [3718d547013c710830e873021b5906c100a1d4b0] location [https://api.github.com/repos/rfennell/SampleRepo/git/commits/3718d547013c710830e873021b5906c100a1d4b0]
2016-11-08T16:52:09.8502002Z ##[warning]Just using the details we have from the build
``` 

So the issue is VSTS does not have the details for a GitHub build. We might be able to work around this by using different properties on the data return - I will look into that next, hopefully a small template change will provide a work around  without the need to make a call to GitHub API which would be a major change.

**Comment by rfennell** [comment] 2016-11-08 17:47
Ok I have workaround, a template change that at least shows the commits and provides links to Github, hope it is enough for you. 

Note the properties used on the $cscommit change. Also note I have put a comment in saying we can't get work items

```
#Release notes for build $defname  
**Build Number**  : $($build.buildnumber)    
**Build started** : $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$build.startTime)  
**Source Branch** $($build.sourceBranch)  
  
###Associated work items  
No VSTS work items associated as repo hosted on GitHub
  
###Associated change sets/commits  
@@CSLOOP@@  
* **ID $($csdetail.id)** [$($csdetail.message)]($($csdetail.displayUri))    
@@CSLOOP@@
```

I have added this sample to the [Wiki resources](https://github.com/rfennell/vNextBuild/blob/master/SampleTemplates/build-githubrepo-template)

**Comment by turowicz** [comment] 2016-11-09 16:29
Thanks, will try it out as soon as I can!

**Comment by rfennell** [comment] 2016-11-09 16:53
Great if it work, close the issue off, if it does let me know and we will see what we can do

**Closed** 2016-11-22 09:58 UTC
Labels: GenerateReleaseNotes

**Comment by turowicz** [comment] 2016-11-22 16:12
Sorry, I didn't manage to apply changes as I'm buried in work. I will get around to it early next week. Sounds ridiculous but this is where things are in a startup ;)

For now let's assume it works.

**Comment by rfennell** [comment] 2016-11-22 16:42
Tell me about it !
