### ISSUE TITLE
Distinguish Assembly<File,Informational>Version Attributes

### ISSUE THREAD

**Issue by KZeronimo** [rfennell/vNextBuild#43] opened 2016-09-29 20:40 UTC
I've been working with your vsts task plugin for handling version numbers and wanted to inquire about your interest regarding building in support for handling each AssembyVersion attribute independently ([reference](https://github.com/johanclasson/vso-agent-tasks)).

I would be will to help out

**Comment by rfennell** [comment] 2016-09-29 21:32
I have no immediate plans to revisit the versioning tasks

But  always happy to have a look a pull requests if you want to submit anything.

**Comment by rfennell** [comment] 2016-10-03 19:08
This is actually a duplicate of #44, which actually calls to provide three different version values

**Comment by rfennell** [comment] 2016-11-08 02:27
This feature has been released in 1.9.x

It has been done by adding an extra field on the Advanced where you can specify the version field to update. If this new parameter field is left empty (the default) the behaviour is as it has been in the past i.e. all version fields are updated.  

This means if you want to specify different values for different field you need to add multiple instances of the task to the build.

**Closed by rfennell** 2016-11-08 02:27 UTC
Labels: duplicate, enhancement, Versioning

**Comment by KZeronimo** [comment] 2016-11-08 13:28
Awesome ... thanks for your work on this Richard
