### ISSUE TITLE
"The version field to update" is blank but all the version fields are not updated

### ISSUE THREAD

**Issue by marcusien** [rfennell/vNextBuild#288] opened 2018-03-28 10:07 UTC
### VSTS Extension you are using
Manifest Versioning Build Tasks : Version .NET Core Assemblies

### Where are you running it?
on-premise TFS 2018 : Version 16.122.27409.2

### Version of Extension/Task
Last version

### Expected behaviour and actual behaviour
Want to update all the version fields inside csproj.
My csproj only contains <AssemblyVersion> filled
I let the "The version field to update" task field blank
After the task done, I expect to have my <AssemblyVersion> updated

Actually, I just have a new "<Version>" field filled, but <AssemblyVersion> is not updated

**Comment by rfennell** [comment] 2018-04-03 12:11
OK I think I understand the problem, I need to write some tests get to the bottom of it

**Comment by rfennell** [comment] 2018-04-03 19:01
There was an error in the logic, I have fixed it and added more unit tests
It has been released as 1.36.1

**Closed by rfennell** 2018-04-03 19:01 UTC
Labels: Versioning, bug

**Comment by techqed** [comment] 2018-04-05 13:41
Hi Richard, this update seems to have broken our build process. We have the *version field to update* as blank in the task definition. In our case we don't have any Version elements in the .csproj and let your versioner add the `Version` element - seems like opposite use case to @marcusien ! :).

It used to add the `<Version>x.y.z</Version>` tag after `</TargetFramework>` or `<TargetFrameworks>` if it was missing from the .csproj. In the latest version it is now not doing anything (and so defaulting to 1.0.0.0) as it doesn't find anything to replace. Let me know if you want me to raise a separate ticket. Thanks, Simon

**Comment by marcusien** [comment] 2018-04-05 14:34
You can force the "version field" to be updated. In your case, just put "Version" inside the "The version field to update" field and it will do the trick.

**Comment by techqed** [comment] 2018-04-05 14:54
Thanks @marcusien. Yes that would work now - we didn't do that originally because it didn't work and I didn't get round to raising a bug report - so thanks for doing that! :) The problem is I will need to edit all of our build definitions for this sort of workaround fix - I have updated some of them to temporarily get some urgent ones working and it does work.

**Comment by rfennell** [comment] 2018-04-05 15:18
Sorry, this is down to my development  errors

The root issue here is that the field parameter documentation (tooltip) said leaving the parameter blank did one thing i.e. updating all the 'version' fields. However, in reality what it did was add a <Version>1.2.3</Version> field. This problem was down to an error in my code and associated poor testing. 

This has caused confusion, as seen in these bug reports, so I needed to fix it. 

All my options ended up being breaking changes of a sort; in the end I decided that treating the parameters options/documentation as being the correct specification was the best option, so made appropriate changes to the logic and added suitable unit tests to test all cases.

Sorry if these changes have caused anyone issues; but I hope that going forward having a tasks that works as expected is worth the pain.

**Comment by marcusien** [comment] 2018-04-05 15:56
@techqed depending on your TFS version, I suggest you to use "Task groups" to "factorize" your jobs. Then, if anything like this happen, you only need to make the change in one place :)

Thanks Richard for the fixes, I still didn't have time to check the last update of your extension :)

**Comment by techqed** [comment] 2018-04-05 16:03
@rfennell don't say that - after seeing you at various DevOps lectures I look up to you as the gold standard! :) Ok, so the option is now either to add a dummy `<Version></Version>` in the csproj and it'll get updated, or specify a '**Version**' in the task definition and it'll get added if it doesn't exist.

@marcusien yes, that is something at some point I plan to get round to doing! :)
