### ISSUE TITLE
View PBI on Release Notes

### ISSUE THREAD

**Issue by miltoncamara** [rfennell/vNextBuild#192] opened 2017-10-26 22:31 UTC
Is possible to get parent work items? People that receive this e-mail is not interesting to view tasks. I think they would like to see the use cases / pbi.

**Comment by ChrisLGardner** [comment] 2017-11-02 22:41
I think it should be possible but I'd have to look into it.

**Comment by SWarnberg** [comment] 2017-11-07 15:37
Same request as #92.

**Comment by rfennell** [comment] 2017-11-14 11:24
I am closing this as it is a duplicate of #92 as stated above. Please follow #92 to track what we are doing over this change

**Closed by rfennell** 2017-11-14 11:24 UTC
Labels: duplicate, GenerateReleaseNotes (Poweshell version), GenerateReleaseNotes (XPlat version), question
