### ISSUE TITLE
Code coverage output not supported on Pester versions before 4.0.4

### ISSUE THREAD

**Issue by balfa666** [rfennell/vNextBuild#356] opened 2018-07-24 11:02 UTC
### VSTS Extension you are using
Pester Test Runner Build Task

### Where are you running it?
on-premise TFS (2018 U1)*

### Version of Extension/Task
8.2.3

### Expected behaviour and actual behaviour

I keep getting the following warning even if i have the lastest version of Pester installed: ##[warning]Code coverage output not supported on Pester versions before 4.0.4.

The (get-module pester).version does not return anything on the server from the following lines in pester.ps1:

if ($CodeCoverageOutputFile -and (Get-Module Pester).Version -ge '4.0.4') 
or 
elseif ($CodeCoverageOutputFile -and (Get-Module Pester).Version -lt '4.0.4')

I added the switch -ListAvailable and everything works

### Steps to reproduce the problem
see above

**Comment by ChrisLGardner** [comment] 2018-07-24 11:15
I've had another report of this from someone else too so I need to have a look at the logic I have in place for importing Pester. It shouldn't ever occur as we're shipping 4.3.1 with the extension and should be falling back to import that if we can't upgrade to a newer version.

I'll try to find some time this week to look at this and get it fixed.

**Comment by balfa666** [comment] 2018-07-24 12:38
Thanks for the quick answer

**Comment by ChrisLGardner** [comment] 2018-08-07 09:34
Sorry for the delay in getting back to you about this @balfa666. I've done some testing but can't reproduce this.

Can you run a build and set the System.Debug variable to True? Then if you look through the logs you should find some lines with `Loading module from path 'D:\a\_tasks\Pester_31ef0033-64e3-4c55-b888-f446541474a6\8.2.3\4.3.1\`. If you don't and it's got a different path there then can you let me know where that path is, such as being one of the normal PSModulePath folders. If it doesn't even attempt to import the module then I'll have to investigate this further.

As a related question, what OS and PS version are your build agents running? I'll see if I can spin up a TFS 2018 instance in some VMs and do some testing with those.

**Comment by balfa666** [comment] 2018-08-07 10:58
I'm running on Windows server 2012 r2 and powershell 5.1.14409.1012. We also have the latest version of Pester installed on the server
Here are the logs for the build with the system.debug variable at true. I could not find the loading of the module in them
[logs_146170.zip](https://github.com/rfennell/vNextBuild/files/2266104/logs_146170.zip)

**Comment by balfa666** [comment] 2018-08-07 11:13
I'm running on Windows server 2012 r2 and powershell 5.1.14409.1012. We also have the latest version of Pester installed on the server

The only thing I can see loading from the folder you specified is : Loading module from path 'D:\b\SBUIMTL401\_tasks\Pester_31ef0033-64e3-4c55-b888-f446541474a6\8.2.3\HelperModule.psm1'.

[1_Build.txt](https://github.com/rfennell/vNextBuild/files/2266157/1_Build.txt)

**Comment by ChrisLGardner** [comment] 2018-08-07 11:42
Looking at that log it appears to be comparing which version of pester is installed locally with the version available on PSGallery and then importing the latest version it finds, which is 4.4.0.

I think I see why it's still showing the warning when it shouldn't be. I'll do some further testing and should have a fix out later today or tomorrow.

**Comment by ChrisLGardner** [comment] 2018-08-07 13:58
I think I've fixed this and released it as 8.3.4 so it should be available to you to update now.

**Comment by deadlydog** [comment] 2018-08-09 23:39
Hey @ChrisLGardner I'm having the same problem, and am using v8.3.4 of the task. I've attached the output with `debug` enabled.

[4_Run Pester tests.txt](https://github.com/rfennell/vNextBuild/files/2276156/4_Run.Pester.tests.txt)

From this bit of the log, it looks like it's finding 2 versions of Pester, but loading up the old version instead of the newer one:
```
2018-08-09T23:34:38.3043854Z ##[debug]Populating RepositorySourceLocation property for module Pester.
2018-08-09T23:34:38.3043854Z ##[debug]Loading module from path 'C:\Users\TFSService\Documents\WindowsPowerShell\Modules\Pester\4.4.0\Pester.psm1'.
2018-08-09T23:34:38.3356389Z ##[debug]Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Pester.psm1'.
2018-08-09T23:34:38.3668921Z Running Pester from the folder [C:\Builds\_work\78\s\*] output sent to [C:\Builds\_work\78\s\Test-Pester.XML]
2018-08-09T23:34:38.3668921Z 
2018-08-09T23:34:38.3668921Z 
2018-08-09T23:34:38.3825178Z ##[warning]Code coverage output not supported on Pester versions before 4.0.4.
2018-08-09T23:34:38.3825178Z ##[debug]Processed: ##vso[task.logissue type=warning]Code coverage output not supported on Pester versions before 4.0.4.
```

And because it's using the older version (3.4.0 in this case) I don't get the code coverage output file.

Hopefully this helps you solve the problem. Thanks for the great extension 👍

**Comment by ChrisLGardner** [comment] 2018-08-10 09:53
@deadlydog Thanks for that log, it helped me pinpoint where that error was coming from. It should be fixed in 8.4.x that I've just released.

**Comment by ChrisLGardner** [comment] 2018-08-22 09:44
With no update in a while I'm going to assume this is fixed now and close the issue. If there are still problems then feel free to reopen it or create a new issue.

**Closed by ChrisLGardner** 2018-08-22 09:44 UTC
Labels: Pester, bug

**Comment by deadlydog** [comment] 2018-08-22 15:37
I can confirm that the problem is fixed and it no longer throws an error. However, my code coverage results are all reporting 0% coverage. I didn't have code coverage setup before encountering this fix though, so I'm not sure if that's related to this, or if it's just a configuration error on my end. At the very least, the original reported bug seems to be fixed.
